TX_POWER = 1;
TX_FREQ = 915e6;
TX_HEIGHT = 10;

siteA = txsite(Name = "SiteA", ...
    Latitude = 35.616437, ...
    Longitude = -111.592136, ...
    AntennaHeight = TX_HEIGHT, ...
    TransmitterFrequency = TX_FREQ, ...
    TransmitterPower = TX_POWER);

siteF = txsite(Name = "SiteF", ...
    Latitude = 35.593743, ...
    Longitude = -111.653278, ...
    AntennaHeight = TX_HEIGHT, ...
    TransmitterFrequency = TX_FREQ, ...
    TransmitterPower = TX_POWER);

siteK = txsite(Name = "SiteK", ...
    Latitude = 35.590627, ...
    Longitude = -111.633156, ...
    AntennaHeight = TX_HEIGHT, ...
    TransmitterFrequency = TX_FREQ, ...
    TransmitterPower = TX_POWER);

siteL = txsite(Name = "SiteL", ...
    Latitude = 35.626898, ...
    Longitude = -111.602013, ...
    AntennaHeight = TX_HEIGHT, ...
    TransmitterFrequency = TX_FREQ, ...
    TransmitterPower = TX_POWER);

pmA = propagationModel("longley-rice", ...
    AntennaPolarization = "vertical", ...
    GroundConductivity = 0.042487, ...
    GroundPermittivity = 6.847824, ...
    AtmosphericRefractivity = 256.3, ...
    ClimateZone = "continental-temperate", ...
    SituationVariabilityTolerance = 0.5, ...
    TimeVariabilityTolerance = 0.9);

pmF = propagationModel("longley-rice", ...
    AntennaPolarization = "vertical", ...
    GroundConductivity = 0.046404, ...
    GroundPermittivity = 5.504067, ...
    AtmosphericRefractivity = 256.3, ...
    ClimateZone = "continental-temperate", ...
    SituationVariabilityTolerance = 0.5, ...
    TimeVariabilityTolerance = 0.9);

pmK = propagationModel("longley-rice", ...
    AntennaPolarization = "vertical", ...
    GroundConductivity = 0.043795, ...
    GroundPermittivity = 7.058396, ...
    AtmosphericRefractivity = 256.3, ...
    ClimateZone = "continental-temperate", ...
    SituationVariabilityTolerance = 0.5, ...
    TimeVariabilityTolerance = 0.9);

pmL = propagationModel("longley-rice", ...
    AntennaPolarization = "vertical", ...
    GroundConductivity = 0.039531, ...
    GroundPermittivity = 6.379993, ...
    AtmosphericRefractivity = 256.3, ...
    ClimateZone = "continental-temperate", ...
    SituationVariabilityTolerance = 0.5, ...
    TimeVariabilityTolerance = 0.9);

[~, ~, ~] = mkdir("../data/itm");

disp("Processing SiteA")
siteAPd = coverage(siteA, pmA, ...
    ReceiverAntennaHeight = 2, ...
    SignalStrengths = -150:0, ...
    MaxRange = 2500, ...
    Resolution = 30);
writetable(siteAPd.Data, "../data/itm/siteA.csv");

disp("Processing SiteF")
siteFPd = coverage(siteF, pmF, ...
    ReceiverAntennaHeight = 2, ...
    SignalStrengths = -150:0, ...
    MaxRange = 2500, ...
    Resolution = 30);
writetable(siteFPd.Data, "../data/itm/siteF.csv");

disp("Processing SiteK")
siteKPd = coverage(siteK, pmK, ...
    ReceiverAntennaHeight = 2, ...
    SignalStrengths = -150:0, ...
    MaxRange = 2500, ...
    Resolution = 30);
writetable(siteKPd.Data, "../data/itm/siteK.csv");

disp("Processing SiteL")
siteLPd = coverage(siteL, pmL, ...
    ReceiverAntennaHeight = 2, ...
    SignalStrengths = -150:0, ...
    MaxRange = 2500, ...
    Resolution = 30);
writetable(siteLPd.Data, "../data/itm/siteL.csv");
