F_CARRIER = 913e6;
F_BANDWIDTH = 20e6;
TEMP = 9.06;

SITE_A_SAND = 43;
SITE_A_CLAY = 18;
SITE_A_SG = 2.7;
SITE_A_VWC = 0.11306;

SITE_F_SAND = 33;
SITE_F_CLAY = 34;
SITE_F_SG = 2.7;
SITE_F_VWC = 0.10839;

SITE_K_SAND = 43;
SITE_K_CLAY = 18;
SITE_K_SG = 2.7;
SITE_K_VWC = 0.1173;

SITE_L_SAND = 43;
SITE_L_CLAY = 18;
SITE_L_SG = 2.7;
SITE_L_VWC = 0.10347;

function [eRS, eRM, eIS, eIM, s] = compute(fCarr, fBand, temp, sand, clay, sg, vwc)
    % Compute middle
    [epsilon, sigma, complexEpsilon] = earthSurfacePermittivity("soil", ...
        fCarr, ...
        temp, ...
        sand, ...
        clay, ...
        sg, ...
        vwc ...
    );

    % Compute sides
    [epsilonLow, sigmaLow, complexEpsilonLow] = earthSurfacePermittivity("soil", ...
        fCarr - (fBand / 2), ...
        temp, ...
        sand, ...
        clay, ...
        sg, ...
        vwc ...
    );
    [epsilonHigh, sigmaHigh, complexEpsilonHigh] = earthSurfacePermittivity("soil", ...
        fCarr + (fBand / 2), ...
        temp, ...
        sand, ...
        clay, ...
        sg, ...
        vwc ...
    );

    % Compute std
    [eRS, eRM] = std([epsilon, epsilonLow, epsilonHigh]);
    [eIS, eIM] = std(imag([complexEpsilon, complexEpsilonLow, complexEpsilonHigh]));
    s = mean([sigma, sigmaLow, sigmaHigh]);
end

[eRS, eRM, eIS, eIM, sigma] = compute( ...
    F_CARRIER, ...
    F_BANDWIDTH, ...
    TEMP, ...
    SITE_A_SAND, ...
    SITE_A_CLAY, ...
    SITE_A_SG, ...
    SITE_A_VWC ...
);
fprintf( ...
    "Site A: eRS: %f, eRM: %f, eIS: %f, eIM: %f, sigma: %f\n", ...
    eRS, eRM, eIS, eIM, sigma ...
);

[eRS, eRM, eIS, eIM, sigma] = compute( ...
    F_CARRIER, ...
    F_BANDWIDTH, ...
    TEMP, ...
    SITE_F_SAND, ...
    SITE_F_CLAY, ...
    SITE_F_SG, ...
    SITE_F_VWC ...
);
fprintf( ...
    "Site F: eRS: %f, eRM: %f, eIS: %f, eIM: %f, sigma: %f\n", ...
    eRS, eRM, eIS, eIM, sigma ...
);


[eRS, eRM, eIS, eIM, sigma] = compute( ...
    F_CARRIER, ...
    F_BANDWIDTH, ...
    TEMP, ...
    SITE_K_SAND, ...
    SITE_K_CLAY, ...
    SITE_K_SG, ...
    SITE_K_VWC ...
);
fprintf( ...
    "Site K: eRS: %f, eRM: %f, eIS: %f, eIM: %f, sigma: %f\n", ...
    eRS, eRM, eIS, eIM, sigma ...
);


[eRS, eRM, eIS, eIM, sigma] = compute( ...
    F_CARRIER, ...
    F_BANDWIDTH, ...
    TEMP, ...
    SITE_L_SAND, ...
    SITE_L_CLAY, ...
    SITE_L_SG, ...
    SITE_L_VWC ...
);
fprintf( ...
    "Site L: eRS: %f, eRM: %f, eIS: %f, eIM: %f, sigma: %f\n", ...
    eRS, eRM, eIS, eIM, sigma ...
);